spring:
  datasource:
    url: jdbc:h2:mem:smile-db
    username: sa
    password:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
    hiddenmethod:
      filter:
        enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          sharedcache:
            mode: ENABLE_SELECTIVE

    generate-ddl: true
    hibernate:
      ddl-auto: create

cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    s3:
      bucket: ${BUCKET_NAME}
      dir: Gyunny/
    region:
      static: ${AWS_REGION}
    stack:
      auto: false